BrOrlandi/GitTrainingWall

- templates/users/andersonsantos.html
> Added template for andersonsantos.

- templates/users/guitufaile.html
Bruno, beleza?
Criei o html sem conseguir rodar o python no meu windows, só editei no sublime o conteudo em cima do template. Se caso não rodar ou der bug por favor deixe para lá.
Muito obrigado,
Guilherme
> Adicionando Template - Guilherme Tufaile

- templates/users/helintonf.html
Obrigado Bruno Orlandi pelo curso.
> Adicionado perfil - helintonf (#11).

- templates/users/rafaelsant.html
Seguindo as instruções do exercício final, foi adicionado o perfil do novo aluno.
> Adicionado aluno Rafael

- templates/users/malkaviano.html
> Malkaviano user page added.

- templates/users/oselame.html
> Oselame user page added.

- templates/users/hellwald.html
Incluido arquivo hellwald.html
> New file templates/users/hellwald.html inserted.

- templates/users/ulyssescaetanobraga.html
> Aluno Ulysses Caetano Braga

- static/styles.css
- templates/index.html
> fixed card layout

- templates/users/tirq.html
Add user tirq to resolve #28 issue.
> Add user tirq to resolve #28

- templates/users/mathvinicius.html
Segue o projeto final do curso de Git e contribuições open source.
> Adicionado correção para o bug no qual faltava meu nome.

- templates/users/claudio.html
Espero que este esteja de acordo pois so estou subindo o arqivo com os meus dados
> Aluno claudio inserido com sucesso

- templates/users/cleitondantas.html
> Adicionando o aluno Cleiton Dantas.

- templates/users/marcellopato.html
Fiz o curso pelo Udemy e esse é o exercício prático que você sugeriu
> Marcello Pato do curso de Git

- templates/users/filipedesousab.html
Adicionando o perfil como solicitado no curso
;D
> Adicionado o perfil filipedesousab.html à templates/users/

- static/styles.css
- templates/users/matheusale.html
adicionei um style ao ícone 'close' dos cards.
Para que ele sempre fique no canto superior direito do card.
> Ajeitadinha no style

- templates/users/antonisganzerla.html
Adicionado card com meu perfil
> adicionado card com meu perfil

- templates/users/leandrooliveira.html
> Adicionando user Leandro Oliveira

- templates/users/davidlucas.html
> Add new user David Lucas

- templates/users/thiago.poliveira.html
Aluno do curso de Git da Udemy. Projeto final de curso.
> Inclusão do aluno Thiago Oliveira

- templates/users/wjuniori.html
Adicionado usuário Washington Júnior como parte do Projeto Final do Curso Git e contribuições para projetos Open Source
> Adicionado usuário Washington Júnior.

- templates/users/josemiltonsampaio.html
Sou aluno do curso de Git da Udemy. Criei meu profile.
> Adicionado aluno Jose Milton Sampaio

- templates/users/cdberga.html
Prezado, segue meu pull-request.
> Adicionado o meu perfil no projeto

- templates/users/robertogomes.html
Tentando subir o arquivo de usuário proposto, usando apenas o guthub.
> robertogomes_user

- templates/users/lucasbelizari.html
Adicionado um novo usuário "Lucas Belizário".
> Branchlucas

- templates/users/troyack.html
Added my user card to the wall.
> Added Eloir Troyack's card.

- templates/users/cristianambrosi.html
> Adicionado novo aluno

- templates/users/nataliaoliveira.html
Fiz dois commits:
1. Adicionei o meu card
2.  Modificações e ajustes no meu card
Waiting for feedback :smiley:
> Adicionar aluna Natália Oliveira

- templates/users/thiagosakurai.html
Incluído o aluno Thiago Sakurai Paschoal
> adicionado o arquivo thiagosakurai.html

- templates/users/wesleydutrads.html
Segue Commit coma conclusao do curso GitHub
> Teste Final

- templates/users/davidwilliam.html
Adicionado aluno David William
> Adicionado aluno David William

- templates/users/williamrm.html
Adicionado template para usuário: WillRy
> Adicionado template para usuario: WillRy

- templates/users/robisonmachado.html
> add student Robison Machado

- templates/users/ozielguimaraes.html
Fiz o Curso e estou enviando o meu perfil.
> Adicionando meu perfil.

- templates/users/felipemarques.html
Realizei o curso de Git e estou entregando o projeto final.
> Adicionando perfil Felipe Marques.

- templates/users/angeloxavier.html
Olá Professor estou criando meu pull request atraves do portal do github. Angelo.
> Adc aluno Angelo Xavier

- templates/users/alexpereiramaranhao.html
Por favor, solicito aprovação para incluir a adição do meu perfil no projeto. Obrigado.
> Adiciona card para o perfil de Alex Pereira Maranhão

- templates/users/jailson.xavier.html
Foi adicionado um novo aluno ao curso.
> Curso Git e GitHub.

- templates/users/ideilsoncisne.html
Performing my first pull request
> Added profile on page

- templates/users/rodrigomoretto.html
Adding user Rodrigo. Hopefully everything is right.
> Adding User Rodrigo

- templates/users/andersonweller.html
> Add user Anderson Weller

- templates/users/diegodias.html
Projeto final do curso da udemy de git
> Adicionando usuário Diego Dias

- templates/users/wmazoni.html
Segue a modificação do exercício final do curso
> Adicionando o meu usuário (wmazoni) ao repositório

- templates/users/diogofalcomer.html
Professor, adicionei meu usuário ao mural. Concluindo o curso de git disponibilizado na udemy.
Abraços!
>  Adicionando Diogo ao mural.

- templates/users/udsonsilva.html
Solicito a adição do template udsonsilva.html ao repositório.
> Adicionado template udsonsilva.

- templates/users/paulopaulino.html
> novo usuario

- templates/users/morenomdz.html
> Added morenomdz user file

- templates/users/eduardogrigoletto.html
Conforme solicitado no exercício final, criado um card com o template colocado na pasta de respectivo nome, com perfil de git e linkedin anexados
> Incluído o quadro do aluno Eduardo Grigoletto

- templates/users/gabrielalves.html
Pull Request com meu usuário do GitHub
> Exercício Final

- templates/users/eduardovantinineto.html
Olá, segue a alteração referente ao trabalho final do curso Git e contribuições para projetos Open Source no Udemy.
> Inserção Eduardo Vantini Neto

- templates/users/leonardomatos.html
> Adicionado Leonardo Matos

- templates/users/alvarosousa.html
São três commits feitos porém apenas um arquivo foi modificado, tive que corrigir um erro após já ter feito um push no repositório.
> Adicionando aluno ao site
